export const WELCOME_NOTE = [
  '---',
  'type: note',
  'title: Welcome to MarkiMarkdown',
  'tags: [markimarkdown]',
  '---',
  '',
  '# Welcome',
  '',
  'In the **middle** is the raw Markdown. On the **right** is the same note, tidied up.',
  'Edit either side and the other keeps up. Try changing *this* word.',
  '',
  'Markdown you will use most:',
  '',
  '- `#` at the start of a line makes a heading',
  '- Two stars around a word make it **bold**',
  '- A dash starts a bullet',
  '',
  'Your turn:',
  '',
  '- [ ] In the Funky Bunch pane on the left, add a skill folder and a domain folder',
  '- [ ] Tick a square in the grid, then press View YAML in the middle pane to see the lines it added',
  '- [ ] Choose a raw folder, tick Archive / distribute, then press Save and archive',
  '',
  '---',
  '',
  'Save keeps this working copy where it is. Archiving also drops a dated copy into your',
  'raw folder, tagged with the skills and domains you ticked. Your second brain takes it from there.',
  ''
].join('\n')
