export const WELCOME_NOTE = [
  '---',
  'type: note',
  'title: Welcome to MarkiMarkdown',
  'tags: [markimarkdown]',
  '---',
  '',
  '# Welcome',
  '',
  'On the **left** is the raw Markdown. On the **right** is the same note, tidied up.',
  'Edit either side and the other keeps up. Try changing *this* word.',
  '',
  'Markdown you will use most:',
  '',
  '- `#` at the start of a line makes a heading',
  '- Two stars around a word make it **bold**',
  '- A dash starts a bullet',
  '',
  'Your turn:',
  '',
  '- [ ] Open the team board (the grid button on the left edge) and add a skill and a domain',
  '- [ ] Make a bunch, pick it, then press File',
  '',
  '---',
  '',
  'Filing writes one copy into the raw folder of the bunch you chose, stamped with',
  'the skills and domains in that bunch. Your second brain takes it from there.',
  ''
].join('\n')
